# Generated by Django 6.1.2 on 2026-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_of_pages',
            field=models.IntegerField(default=0),
        ),
    ]
